import { IconArrowNarrowRight } from "@tabler/icons-react";
import Container from "./container";
import Heading from "./heading";
import SubHeading from "./subHeading";
import { Button } from "./ui/button";
import LandingImage from "./landingImage";
import Link from "next/link";

const Hero = () => {
  return (
    <section className="pt-10 md:pt-20 lg:pt-32">
      <Container>
        <Heading size="h1">
          Customer support that <br /> feels like a conversation.
        </Heading>

        <SubHeading className="py-8">
          Simplify your shared inbox, collaborate effortlessly, and give every
          customer a reply that feels personal — even if it was generated by a
          bot.
        </SubHeading>

        {/* CTA Buttons will go here */}
        <div className="flex items-center gap-6">
          <Button className="cursor-pointer px-5 py-5">Start free trial</Button>
          <Link
            href="/how-it-works"
            className="group inline-flex items-center gap-2 rounded-full px-4 py-3 text-sm font-medium text-neutral-800 transition-all hover:bg-neutral-400/60 dark:text-neutral-200 hover:dark:bg-neutral-800/80"
          >
            See how it works
            <IconArrowNarrowRight className="size-4 transition-transform group-hover:translate-x-1" />
          </Link>
        </div>
        {/* HeroImage */}
        <LandingImage />
      </Container>
    </section>
  );
};

export default Hero;
